### ISSUE TITLE
Poster does not work

### ISSUE THREAD

**Issue by ItsNash0** [zcuric/plyrue#19]
I can't get the poster to work at all, just black player until video plays

**Comment by zcuric** [comment]
@ItsNash0 can you provide code samples of how you use it?

**Comment by ItsNash0** [comment]
` <plyrue
          ref="plyrue"
          :poster="video.image"
          type="video"
          class="max-w-full"
          :options="options"
          :sources="sources"
        />`
it seems the plyrue component has the prop. but not the plyrueVideo
thats it really, does it work on your end?
@zcuric

**Comment by linking2014** [comment]
same issue

**Comment by linking2014** [comment]
> ` <plyrue ref="plyrue" :poster="video.image" type="video" class="max-w-full" :options="options" :sources="sources" />`
> it seems the plyrue component has the prop. but not the plyrueVideo
> thats it really, does it work on your end?
> @zcuric

i have same issue, resloved by update the poster manually each time my player component init
``` javascript
if (this.$refs.plyr.player) {
    this.$refs.plyr.player.poster = this.$util.imgSrc(this.poster, 75, 1920, 1080) // 更新海报
}
```

**Comment by zcuric** [comment]
@linking2014 I'll check today and realease a fix.

**Comment by zcuric** [comment]
What version are u using @linking2014  and @ItsNash0? 
Poster is set here and it applies in all cases: https://github.com/zcuric/plyrue/blob/master/src/components/Plyrue.vue#L39

**Comment by linking2014** [comment]
> What version are u using @linking2014 and @ItsNash0?
> Poster is set here and it applies in all cases: https://github.com/zcuric/plyrue/blob/master/src/components/Plyrue.vue#L39

i use the latest version, in fact the problem is the poster did not change when you change the src like `:poster="src"` dynamically

**Comment by ItsNash0** [comment]
right, im using it like that, dynamically

**Comment by zcuric** [comment]
@ItsNash0 can you give an example of using it dynamically? Are you changing posters dynamically or the sources?

**Comment by linking2014** [comment]
@zcuric here's a demo 
[https://codepen.io/linking2014/pen/RwGKXRR](https://codepen.io/linking2014/pen/RwGKXRR)

**Comment by zcuric** [comment]
@linking2014 This not a bug, it's technically a new feature, so it's available  now in v.2.3.0, please check :)

**Comment by linking2014** [comment]
@zcuric it's ok now, thanks

**Comment by zcuric** [comment]
@ItsNash0 Does it work for you?
