### ISSUE TITLE
"this.media is null" on @timeupdate event

### ISSUE THREAD

**Issue by francoism90** [zcuric/plyrue#8]
**Describe the bug**
```
// player.vue
<template>
  plyrue(
    id="player"
    type="video"
    ref="plyrue"
    :poster="data.thumbnail"
    :src="data.stream_url"
    :emit="['loadedmetadata', 'timeupdate', 'playing', 'pause', 'ended']"
    :options="options"
    @loadedmetadata="setMetadata()"
    @playing="setStatus('playing')"
    @pause="setStatus('pause')"
    @ended="setStatus('ended')"
    @timeupdate="setCurrentTime(player.currentTime)"
    crossorigin
    autoplay
  )
...
```

**To Reproduce**
1. Pick a video from overview
2. Video plays and @timeupdate works
3. Go back to history (history.back())
4. Pick a video from overview
5. Video plays, but @timeupdate throws `this.media is null` and doesn't work anymore

**Expected behavior**
Is the event being cleared correctly?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox Developer Edition
 - Version: 70

**Additional context**
Using vue-router, Laravel 6 with latest packages.

**Comment by zcuric** [comment]
Thanks, I'll look into it as soon as possible.

**Comment by zcuric** [comment]
@francoism90 I couldn't not reproduce on repository example. Can you maybe reproduce it on repo example, or provide more on how to reproduce? 

Also, from what I seen on here https://github.com/sampotts/plyr/pull/1505 and here https://github.com/sampotts/plyr/issues/1441 it looks like it could be plyr's own problem.

**Comment by francoism90** [comment]
@zcuric Thanks for testing and taking a look at the error. :)

It seems it can be solved by destroying the player using the `beforeDestroy` hook:
```
  computed: {
    player () {
      return this.$refs.plyrue.player
    }
  },
  beforeDestroy () {
    this.player.destroy()
  },
```
Don't know if the linked PR will fix this issue,  or something else is causing it. It doesn't seem to be related to this package however. :)

**Comment by zcuric** [comment]
@francoism90 Thanks for feedback. We do destroy player in `beforeDestroy` https://github.com/zcuric/plyrue/blob/master/src/components/Plyrue.vue#L43

If you encounter it again try to isolate it and please do give feedback again. 

Cheers!

**Comment by francoism90** [comment]
@zcuric I've found out this seem to happen when using `autoplay`.

As a workaround I'm now waiting for event `ready` and wrap the instance in a try/catch just to prevent a warning from being shown:
https://github.com/francoism90/mediadb/blob/master/src/resources/js/components/player/Instance.vue#L65

**Comment by zcuric** [comment]
@francoism90 Can you maybe find a solution for this problem and submit a PR?

**Comment by francoism90** [comment]
@zcuric I really don't know what the solution would be. I think this is normal behavior when using `autoplay` and not (pre)loading the media first.

**Comment by francoism90** [comment]
@zcuric This seems to happen when using keep-alive. I've done some code refactoring on my side and the issue seem to be solved.

Thanks for looking into this issue!
